/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task System API
 * API для управления задачами и студентами
 * OpenAPI spec version: 1.0.0
 */
import { createInstance } from './api-instance';
import type { BodyType } from './api-instance';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export interface AdminRegistration {
  /** @maxLength 254 */
  email: string;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 50 */
  surname: string;
  /** @maxLength 50 */
  patronymic?: string;
  /** @minLength 6 */
  password: string;
  /** @minLength 6 */
  password2: string;
}

export interface AnswerOut {
  id: number;
  text: string;
}

export interface MarkupItemOut {
  start: number;
  end: number;
  style: string;
}

export interface QuestionOut {
  id: number;
  question: string;
  answer: string;
}

export interface CharacteristicResult {
  name: string;
  color: string;
  /** @nullable */
  studentCharacteristics: string | null;
  /** @nullable */
  correctCharacteristics: string | null;
}

export interface EvaluationResult {
  /** Отлично / Хорошо / Удовлетворительно / Попробуйте еще раз */
  grade: string;
  spent_time: string;
  /** Текст задачи */
  text: string;
  studentAnswer: AnswerOut;
  correctAnswer: AnswerOut;
  studentMarkup: MarkupItemOut[];
  correctMarkup: MarkupItemOut[];
  studentQuestions: QuestionOut[];
  correctQuestions: QuestionOut[];
  characteristics: CharacteristicResult[];
}

export interface AdminSubmissionDetailResponse {
  data: EvaluationResult;
  ok: boolean;
}

export interface AnswerOptionInTask {
  id: number;
  text: string;
}

export interface CategoryConfigCRUD {
  readonly id: number;
  /** @maxLength 255 */
  button_title: string;
  short_description: string;
  detail_description: string;
  category: number;
}

export interface CategoryMarkup {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  /**
     * @maxLength 50
     * @pattern ^[-a-zA-Z0-9_]+$
     */
  slug: string;
  color_markup: number;
  task_category: number;
  readonly style: string;
}

export interface CharacteristicOption {
  id: string;
  name: string;
}

export interface CharacteristicInTask {
  id: string;
  name: string;
  color: string;
  options: CharacteristicOption[];
}

export interface ColorsMarkup {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 255 */
  style: string;
}

export interface SubmitResult {
  grade: string;
  spent_time: string;
  text: string;
  /** ID сохранённой попытки */
  submission_id: number;
  studentAnswer: AnswerOut;
  correctAnswer: AnswerOut;
  studentMarkup: MarkupItemOut[];
  correctMarkup: MarkupItemOut[];
  studentQuestions: QuestionOut[];
  correctQuestions: QuestionOut[];
  characteristics: CharacteristicResult[];
}

export interface ControlSubmitResponse {
  data: SubmitResult;
  ok: boolean;
}

export interface QuestionInTask {
  id: string;
  text: string;
  answer: string;
}

export interface TaskStudentSchema {
  id: string;
  text: string;
  characteristics: CharacteristicInTask[];
  questions: QuestionInTask[];
  answerOptions: AnswerOptionInTask[];
}

export interface ControlTaskResponse {
  data: TaskStudentSchema;
  ok: boolean;
}

export interface CookieTokenRefresh {
  readonly access: string;
}

export interface DeletedData {
  detail: string;
}

export interface DeletedResponse {
  ok: boolean;
  data: DeletedData;
}

export interface EducationSubmitResponse {
  data: EvaluationResult;
  ok: boolean;
}

export interface EducationTasksResponse {
  ok: boolean;
  data: TaskStudentSchema[];
}

export interface ErrorResponse {
  ok: boolean;
  error: string;
}

export interface LoginData {
  detail: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  ok: boolean;
  data: LoginData;
}

export interface LogoutData {
  detail: string;
}

export interface LogoutResponse {
  ok: boolean;
  data: LogoutData;
}

export interface MarkupItemIn {
  start: number;
  end: number;
  category_slug: string;
}

export interface MarkupOption {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  /**
     * @maxLength 50
     * @pattern ^[-a-zA-Z0-9_]+$
     */
  slug: string;
  category_markup: number;
}

export interface OkAdminRegistration {
  ok: boolean;
  data: AdminRegistration;
}

export interface OkCategoryConfigCRUD {
  ok: boolean;
  data: CategoryConfigCRUD;
}

export interface OkCategoryMarkup {
  ok: boolean;
  data: CategoryMarkup;
}

export interface OkColorsMarkup {
  ok: boolean;
  data: ColorsMarkup;
}

export interface OkMarkupOption {
  ok: boolean;
  data: MarkupOption;
}

export interface StudentRegistration {
  /** @maxLength 254 */
  email: string;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 50 */
  surname: string;
  /** @maxLength 50 */
  patronymic?: string;
  /** @minLength 6 */
  password: string;
  /** @minLength 6 */
  password2: string;
  group: string;
}

export interface OkStudentRegistration {
  ok: boolean;
  data: StudentRegistration;
}

export interface Submission {
  readonly id: number;
  /** @nullable */
  start_time?: string | null;
  readonly created_at: string;
  /**
     * @maxLength 10
     * @nullable
     */
  spent_time?: string | null;
  answer_markup?: unknown;
  selected_question_ids?: unknown;
  student_characteristics?: unknown;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     * @nullable
     */
  selected_answer_id?: number | null;
  total_score?: number;
  /**
     * @maxLength 50
     * @nullable
     */
  grade?: string | null;
  task: number;
  student: number;
}

export interface OkSubmission {
  ok: boolean;
  data: Submission;
}

export interface TaskAdmin {
  readonly id: number;
  text: string;
  condition: string;
  reference_markup?: unknown;
  correct_characteristics?: unknown;
  category: number;
  complexity: number;
}

export interface OkTaskAdmin {
  ok: boolean;
  data: TaskAdmin;
}

export interface TaskAnswerAdmin {
  readonly id: number;
  /** @maxLength 255 */
  text: string;
  is_correct?: boolean;
  task: number;
}

export interface OkTaskAnswerAdmin {
  ok: boolean;
  data: TaskAnswerAdmin;
}

export interface TaskCategoryCRUD {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /**
     * @maxLength 50
     * @pattern ^[-a-zA-Z0-9_]+$
     */
  slug: string;
}

export interface OkTaskCategoryCRUD {
  ok: boolean;
  data: TaskCategoryCRUD;
}

export interface TaskComplexity {
  readonly id: number;
  /** @maxLength 50 */
  name: string;
  /**
     * @minimum 0
     * @maximum 32767
     */
  level: number;
}

export interface OkTaskComplexity {
  ok: boolean;
  data: TaskComplexity;
}

export interface TaskQuestionAdmin {
  readonly id: number;
  text: string;
  answer: string;
  is_correct?: boolean;
  task: number;
}

export interface OkTaskQuestionAdmin {
  ok: boolean;
  data: TaskQuestionAdmin;
}

/**
 * * `SUPERADMIN` - Главный администратор
* `ADMIN` - Администратор
* `STUDENT` - Студент
 */
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];


export const RoleEnum = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  STUDENT: 'STUDENT',
} as const;

export interface UserProfile {
  readonly id: number;
  readonly email: string;
  readonly name: string;
  readonly surname: string;
  readonly patronymic: string;
  readonly role: RoleEnum;
  readonly group: string;
  readonly is_staff: boolean;
}

export interface OkUserProfile {
  readonly id: number;
  readonly email: string;
  readonly name: string;
  readonly surname: string;
  readonly patronymic: string;
  readonly role: RoleEnum;
  readonly group: string;
  readonly is_staff: boolean;
}

export interface PatchedCategoryConfigCRUD {
  readonly id?: number;
  /** @maxLength 255 */
  button_title?: string;
  short_description?: string;
  detail_description?: string;
  category?: number;
}

export interface PatchedCategoryMarkup {
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
  /**
     * @maxLength 50
     * @pattern ^[-a-zA-Z0-9_]+$
     */
  slug?: string;
  color_markup?: number;
  task_category?: number;
  readonly style?: string;
}

export interface PatchedColorsMarkup {
  readonly id?: number;
  /** @maxLength 100 */
  name?: string;
  /** @maxLength 255 */
  style?: string;
}

export interface PatchedMarkupOption {
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
  /**
     * @maxLength 50
     * @pattern ^[-a-zA-Z0-9_]+$
     */
  slug?: string;
  category_markup?: number;
}

export interface PatchedSubmission {
  readonly id?: number;
  /** @nullable */
  start_time?: string | null;
  readonly created_at?: string;
  /**
     * @maxLength 10
     * @nullable
     */
  spent_time?: string | null;
  answer_markup?: unknown;
  selected_question_ids?: unknown;
  student_characteristics?: unknown;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     * @nullable
     */
  selected_answer_id?: number | null;
  total_score?: number;
  /**
     * @maxLength 50
     * @nullable
     */
  grade?: string | null;
  task?: number;
  student?: number;
}

export interface PatchedTaskAdmin {
  readonly id?: number;
  text?: string;
  condition?: string;
  reference_markup?: unknown;
  correct_characteristics?: unknown;
  category?: number;
  complexity?: number;
}

export interface PatchedTaskAnswerAdmin {
  readonly id?: number;
  /** @maxLength 255 */
  text?: string;
  is_correct?: boolean;
  task?: number;
}

export interface PatchedTaskCategoryCRUD {
  readonly id?: number;
  /** @maxLength 100 */
  name?: string;
  /**
     * @maxLength 50
     * @pattern ^[-a-zA-Z0-9_]+$
     */
  slug?: string;
}

export interface PatchedTaskComplexity {
  readonly id?: number;
  /** @maxLength 50 */
  name?: string;
  /**
     * @minimum 0
     * @maximum 32767
     */
  level?: number;
}

export interface PatchedTaskQuestionAdmin {
  readonly id?: number;
  text?: string;
  answer?: string;
  is_correct?: boolean;
  task?: number;
}

export interface StudentStatement {
  readonly student_fio: string;
  readonly group: string;
  readonly last_start: string;
  readonly last_end: string;
  readonly last_spent: string;
  readonly last_grade: string;
  readonly attempts: string;
}

export interface StudentSubmissionDetailResponse {
  data: EvaluationResult;
  ok: boolean;
}

/**
 * Ключ — slug характеристики, значение — slug опции. Пример: {"strength": "strong"}
 */
export type SubmitRequestStudentCharacteristics = {[key: string]: string};

export interface SubmitRequest {
  /** ID задачи */
  task_id: string;
  /** Затраченное время HH:MM:SS */
  time_spent: string;
  /** ISO datetime начала, напр. '2025-01-15T10:00:00' */
  start_time?: string;
  answer_markup: MarkupItemIn[];
  /** ID вопросов чат-бота, которые задал студент */
  selected_question_ids?: string[];
  /** Ключ — slug характеристики, значение — slug опции. Пример: {"strength": "strong"} */
  student_characteristics?: SubmitRequestStudentCharacteristics;
  /** ID выбранного варианта финального ответа */
  selected_answer_id?: number;
}

export type SchemaRetrieveParams = {
format?: SchemaRetrieveFormat;
lang?: SchemaRetrieveLang;
};

export type SchemaRetrieveFormat = typeof SchemaRetrieveFormat[keyof typeof SchemaRetrieveFormat];


export const SchemaRetrieveFormat = {
  json: 'json',
  yaml: 'yaml',
} as const;

export type SchemaRetrieveLang = typeof SchemaRetrieveLang[keyof typeof SchemaRetrieveLang];


export const SchemaRetrieveLang = {
  af: 'af',
  ar: 'ar',
  'ar-dz': 'ar-dz',
  ast: 'ast',
  az: 'az',
  be: 'be',
  bg: 'bg',
  bn: 'bn',
  br: 'br',
  bs: 'bs',
  ca: 'ca',
  ckb: 'ckb',
  cs: 'cs',
  cy: 'cy',
  da: 'da',
  de: 'de',
  dsb: 'dsb',
  el: 'el',
  en: 'en',
  'en-au': 'en-au',
  'en-gb': 'en-gb',
  eo: 'eo',
  es: 'es',
  'es-ar': 'es-ar',
  'es-co': 'es-co',
  'es-mx': 'es-mx',
  'es-ni': 'es-ni',
  'es-ve': 'es-ve',
  et: 'et',
  eu: 'eu',
  fa: 'fa',
  fi: 'fi',
  fr: 'fr',
  fy: 'fy',
  ga: 'ga',
  gd: 'gd',
  gl: 'gl',
  he: 'he',
  hi: 'hi',
  hr: 'hr',
  hsb: 'hsb',
  hu: 'hu',
  hy: 'hy',
  ia: 'ia',
  id: 'id',
  ig: 'ig',
  io: 'io',
  is: 'is',
  it: 'it',
  ja: 'ja',
  ka: 'ka',
  kab: 'kab',
  kk: 'kk',
  km: 'km',
  kn: 'kn',
  ko: 'ko',
  ky: 'ky',
  lb: 'lb',
  lt: 'lt',
  lv: 'lv',
  mk: 'mk',
  ml: 'ml',
  mn: 'mn',
  mr: 'mr',
  ms: 'ms',
  my: 'my',
  nb: 'nb',
  ne: 'ne',
  nl: 'nl',
  nn: 'nn',
  os: 'os',
  pa: 'pa',
  pl: 'pl',
  pt: 'pt',
  'pt-br': 'pt-br',
  ro: 'ro',
  ru: 'ru',
  sk: 'sk',
  sl: 'sl',
  sq: 'sq',
  sr: 'sr',
  'sr-latn': 'sr-latn',
  sv: 'sv',
  sw: 'sw',
  ta: 'ta',
  te: 'te',
  tg: 'tg',
  th: 'th',
  tk: 'tk',
  tr: 'tr',
  tt: 'tt',
  udm: 'udm',
  uk: 'uk',
  ur: 'ur',
  uz: 'uz',
  vi: 'vi',
  'zh-hans': 'zh-hans',
  'zh-hant': 'zh-hant',
} as const;

export type SchemaRetrieve200One = {[key: string]: unknown};

export type SchemaRetrieve200Two = {[key: string]: unknown};

export type SchemaRetrieve200Three = {[key: string]: unknown};

export type SchemaRetrieve200Four = {[key: string]: unknown};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Возвращает полный разбор: покраска студента vs эталон, выбранный и правильный ответ, вопросы, характеристики.
 * @summary Детальный просмотр конкретной попытки студента
 */
export const adminSubmissionsRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<AdminSubmissionDetailResponse>>,) => {
      return createInstance<AdminSubmissionDetailResponse>(
      {url: `/admin/submissions/${id}/`, method: 'GET'
    },
      options);
    }

/**
 * @summary Сводная таблица: все студенты со сданными попытками
 */
export const adminSubmissionsAllList = (

 options?: SecondParameter<typeof createInstance<StudentStatement[]>>,) => {
      return createInstance<StudentStatement[]>(
      {url: `/admin/submissions/all/`, method: 'GET'
    },
      options);
    }

export const answerRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkTaskAnswerAdmin>>,) => {
      return createInstance<OkTaskAnswerAdmin>(
      {url: `/answer/${id}/`, method: 'GET'
    },
      options);
    }

export const answerDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/answer/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const answerUpdateUpdate = (
    id: number,
    taskAnswerAdmin: BodyType<NonReadonly<TaskAnswerAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskAnswerAdmin>>,) => {
      return createInstance<OkTaskAnswerAdmin>(
      {url: `/answer/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taskAnswerAdmin
    },
      options);
    }

export const answerUpdatePartialUpdate = (
    id: number,
    patchedTaskAnswerAdmin: BodyType<NonReadonly<PatchedTaskAnswerAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskAnswerAdmin>>,) => {
      return createInstance<OkTaskAnswerAdmin>(
      {url: `/answer/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedTaskAnswerAdmin
    },
      options);
    }

export const answerAllList = (

 options?: SecondParameter<typeof createInstance<TaskAnswerAdmin[]>>,) => {
      return createInstance<TaskAnswerAdmin[]>(
      {url: `/answer/all/`, method: 'GET'
    },
      options);
    }

export const answerCreateCreate = (
    taskAnswerAdmin: BodyType<NonReadonly<TaskAnswerAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskAnswerAdmin>>,) => {
      return createInstance<OkTaskAnswerAdmin>(
      {url: `/answer/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskAnswerAdmin
    },
      options);
    }

export const authLoginCreate = (
    loginRequest: BodyType<LoginRequest>,
 options?: SecondParameter<typeof createInstance<LoginResponse>>,) => {
      return createInstance<LoginResponse>(
      {url: `/auth/login/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      options);
    }

export const authLogoutCreate = (

 options?: SecondParameter<typeof createInstance<LogoutResponse>>,) => {
      return createInstance<LogoutResponse>(
      {url: `/auth/logout/`, method: 'POST'
    },
      options);
    }

/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authRefreshTokenCreate = (
    cookieTokenRefresh: BodyType<NonReadonly<CookieTokenRefresh>>,
 options?: SecondParameter<typeof createInstance<CookieTokenRefresh>>,) => {
      return createInstance<CookieTokenRefresh>(
      {url: `/auth/refresh_token/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cookieTokenRefresh
    },
      options);
    }

export const authRegisterAdminCreate = (
    adminRegistration: BodyType<AdminRegistration>,
 options?: SecondParameter<typeof createInstance<OkAdminRegistration>>,) => {
      return createInstance<OkAdminRegistration>(
      {url: `/auth/register/admin/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminRegistration
    },
      options);
    }

export const authRegisterStudentCreate = (
    studentRegistration: BodyType<StudentRegistration>,
 options?: SecondParameter<typeof createInstance<OkStudentRegistration>>,) => {
      return createInstance<OkStudentRegistration>(
      {url: `/auth/register/student/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: studentRegistration
    },
      options);
    }

export const categoryConfigRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkCategoryConfigCRUD>>,) => {
      return createInstance<OkCategoryConfigCRUD>(
      {url: `/category-config/${id}/`, method: 'GET'
    },
      options);
    }

export const categoryConfigDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/category-config/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const categoryConfigUpdateUpdate = (
    id: number,
    categoryConfigCRUD: BodyType<NonReadonly<CategoryConfigCRUD>>,
 options?: SecondParameter<typeof createInstance<OkCategoryConfigCRUD>>,) => {
      return createInstance<OkCategoryConfigCRUD>(
      {url: `/category-config/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryConfigCRUD
    },
      options);
    }

export const categoryConfigUpdatePartialUpdate = (
    id: number,
    patchedCategoryConfigCRUD: BodyType<NonReadonly<PatchedCategoryConfigCRUD>>,
 options?: SecondParameter<typeof createInstance<OkCategoryConfigCRUD>>,) => {
      return createInstance<OkCategoryConfigCRUD>(
      {url: `/category-config/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedCategoryConfigCRUD
    },
      options);
    }

export const categoryConfigAllList = (

 options?: SecondParameter<typeof createInstance<CategoryConfigCRUD[]>>,) => {
      return createInstance<CategoryConfigCRUD[]>(
      {url: `/category-config/all/`, method: 'GET'
    },
      options);
    }

export const categoryConfigCreateCreate = (
    categoryConfigCRUD: BodyType<NonReadonly<CategoryConfigCRUD>>,
 options?: SecondParameter<typeof createInstance<OkCategoryConfigCRUD>>,) => {
      return createInstance<OkCategoryConfigCRUD>(
      {url: `/category-config/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryConfigCRUD
    },
      options);
    }

export const colorsRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkColorsMarkup>>,) => {
      return createInstance<OkColorsMarkup>(
      {url: `/colors/${id}/`, method: 'GET'
    },
      options);
    }

export const colorsDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/colors/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const colorsUpdateUpdate = (
    id: number,
    colorsMarkup: BodyType<NonReadonly<ColorsMarkup>>,
 options?: SecondParameter<typeof createInstance<OkColorsMarkup>>,) => {
      return createInstance<OkColorsMarkup>(
      {url: `/colors/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: colorsMarkup
    },
      options);
    }

export const colorsUpdatePartialUpdate = (
    id: number,
    patchedColorsMarkup: BodyType<NonReadonly<PatchedColorsMarkup>>,
 options?: SecondParameter<typeof createInstance<OkColorsMarkup>>,) => {
      return createInstance<OkColorsMarkup>(
      {url: `/colors/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedColorsMarkup
    },
      options);
    }

export const colorsAllList = (

 options?: SecondParameter<typeof createInstance<ColorsMarkup[]>>,) => {
      return createInstance<ColorsMarkup[]>(
      {url: `/colors/all/`, method: 'GET'
    },
      options);
    }

export const colorsCreateCreate = (
    colorsMarkup: BodyType<NonReadonly<ColorsMarkup>>,
 options?: SecondParameter<typeof createInstance<OkColorsMarkup>>,) => {
      return createInstance<OkColorsMarkup>(
      {url: `/colors/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: colorsMarkup
    },
      options);
    }

export const complexityRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkTaskComplexity>>,) => {
      return createInstance<OkTaskComplexity>(
      {url: `/complexity/${id}/`, method: 'GET'
    },
      options);
    }

export const complexityDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/complexity/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const complexityUpdateUpdate = (
    id: number,
    taskComplexity: BodyType<NonReadonly<TaskComplexity>>,
 options?: SecondParameter<typeof createInstance<OkTaskComplexity>>,) => {
      return createInstance<OkTaskComplexity>(
      {url: `/complexity/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taskComplexity
    },
      options);
    }

export const complexityUpdatePartialUpdate = (
    id: number,
    patchedTaskComplexity: BodyType<NonReadonly<PatchedTaskComplexity>>,
 options?: SecondParameter<typeof createInstance<OkTaskComplexity>>,) => {
      return createInstance<OkTaskComplexity>(
      {url: `/complexity/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedTaskComplexity
    },
      options);
    }

export const complexityAllList = (

 options?: SecondParameter<typeof createInstance<TaskComplexity[]>>,) => {
      return createInstance<TaskComplexity[]>(
      {url: `/complexity/all/`, method: 'GET'
    },
      options);
    }

export const complexityCreateCreate = (
    taskComplexity: BodyType<NonReadonly<TaskComplexity>>,
 options?: SecondParameter<typeof createInstance<OkTaskComplexity>>,) => {
      return createInstance<OkTaskComplexity>(
      {url: `/complexity/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskComplexity
    },
      options);
    }

/**
 * @summary Получить вариант характеристики
 */
export const markupOptionRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkMarkupOption>>,) => {
      return createInstance<OkMarkupOption>(
      {url: `/markup-option/${id}/`, method: 'GET'
    },
      options);
    }

export const markupOptionDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/markup-option/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const markupOptionUpdateUpdate = (
    id: number,
    markupOption: BodyType<NonReadonly<MarkupOption>>,
 options?: SecondParameter<typeof createInstance<OkMarkupOption>>,) => {
      return createInstance<OkMarkupOption>(
      {url: `/markup-option/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: markupOption
    },
      options);
    }

export const markupOptionUpdatePartialUpdate = (
    id: number,
    patchedMarkupOption: BodyType<NonReadonly<PatchedMarkupOption>>,
 options?: SecondParameter<typeof createInstance<OkMarkupOption>>,) => {
      return createInstance<OkMarkupOption>(
      {url: `/markup-option/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedMarkupOption
    },
      options);
    }

/**
 * @summary Все варианты характеристик
 */
export const markupOptionAllList = (

 options?: SecondParameter<typeof createInstance<MarkupOption[]>>,) => {
      return createInstance<MarkupOption[]>(
      {url: `/markup-option/all/`, method: 'GET'
    },
      options);
    }

/**
 * @summary Создать вариант характеристики
 */
export const markupOptionCreateCreate = (
    markupOption: BodyType<NonReadonly<MarkupOption>>,
 options?: SecondParameter<typeof createInstance<OkMarkupOption>>,) => {
      return createInstance<OkMarkupOption>(
      {url: `/markup-option/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: markupOption
    },
      options);
    }

export const markupRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkCategoryMarkup>>,) => {
      return createInstance<OkCategoryMarkup>(
      {url: `/markup/${id}/`, method: 'GET'
    },
      options);
    }

export const markupDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/markup/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const markupUpdateUpdate = (
    id: number,
    categoryMarkup: BodyType<NonReadonly<CategoryMarkup>>,
 options?: SecondParameter<typeof createInstance<OkCategoryMarkup>>,) => {
      return createInstance<OkCategoryMarkup>(
      {url: `/markup/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryMarkup
    },
      options);
    }

export const markupUpdatePartialUpdate = (
    id: number,
    patchedCategoryMarkup: BodyType<NonReadonly<PatchedCategoryMarkup>>,
 options?: SecondParameter<typeof createInstance<OkCategoryMarkup>>,) => {
      return createInstance<OkCategoryMarkup>(
      {url: `/markup/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedCategoryMarkup
    },
      options);
    }

export const markupAllList = (

 options?: SecondParameter<typeof createInstance<CategoryMarkup[]>>,) => {
      return createInstance<CategoryMarkup[]>(
      {url: `/markup/all/`, method: 'GET'
    },
      options);
    }

export const markupCreateCreate = (
    categoryMarkup: BodyType<NonReadonly<CategoryMarkup>>,
 options?: SecondParameter<typeof createInstance<OkCategoryMarkup>>,) => {
      return createInstance<OkCategoryMarkup>(
      {url: `/markup/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryMarkup
    },
      options);
    }

/**
 * @summary Профиль текущего авторизованного пользователя
 */
export const profileRetrieve = (

 options?: SecondParameter<typeof createInstance<OkUserProfile>>,) => {
      return createInstance<OkUserProfile>(
      {url: `/profile/`, method: 'GET'
    },
      options);
    }

export const questionRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkTaskQuestionAdmin>>,) => {
      return createInstance<OkTaskQuestionAdmin>(
      {url: `/question/${id}/`, method: 'GET'
    },
      options);
    }

export const questionDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/question/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const questionUpdateUpdate = (
    id: number,
    taskQuestionAdmin: BodyType<NonReadonly<TaskQuestionAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskQuestionAdmin>>,) => {
      return createInstance<OkTaskQuestionAdmin>(
      {url: `/question/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taskQuestionAdmin
    },
      options);
    }

export const questionUpdatePartialUpdate = (
    id: number,
    patchedTaskQuestionAdmin: BodyType<NonReadonly<PatchedTaskQuestionAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskQuestionAdmin>>,) => {
      return createInstance<OkTaskQuestionAdmin>(
      {url: `/question/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedTaskQuestionAdmin
    },
      options);
    }

export const questionAllList = (

 options?: SecondParameter<typeof createInstance<TaskQuestionAdmin[]>>,) => {
      return createInstance<TaskQuestionAdmin[]>(
      {url: `/question/all/`, method: 'GET'
    },
      options);
    }

export const questionCreateCreate = (
    taskQuestionAdmin: BodyType<NonReadonly<TaskQuestionAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskQuestionAdmin>>,) => {
      return createInstance<OkTaskQuestionAdmin>(
      {url: `/question/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskQuestionAdmin
    },
      options);
    }

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.

- YAML: application/vnd.oai.openapi
- JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = (
    params?: SchemaRetrieveParams,
 options?: SecondParameter<typeof createInstance<Blob | SchemaRetrieve200Two | SchemaRetrieve200Three | SchemaRetrieve200Four>>,) => {
      return createInstance<Blob | SchemaRetrieve200Two | SchemaRetrieve200Three | SchemaRetrieve200Four>(
      {url: `/schema/`, method: 'GET',
        params
    },
      options);
    }

export const submissionRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkSubmission>>,) => {
      return createInstance<OkSubmission>(
      {url: `/submission/${id}/`, method: 'GET'
    },
      options);
    }

export const submissionDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/submission/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const submissionUpdateUpdate = (
    id: number,
    submission: BodyType<NonReadonly<Submission>>,
 options?: SecondParameter<typeof createInstance<OkSubmission>>,) => {
      return createInstance<OkSubmission>(
      {url: `/submission/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: submission
    },
      options);
    }

export const submissionUpdatePartialUpdate = (
    id: number,
    patchedSubmission: BodyType<NonReadonly<PatchedSubmission>>,
 options?: SecondParameter<typeof createInstance<OkSubmission>>,) => {
      return createInstance<OkSubmission>(
      {url: `/submission/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedSubmission
    },
      options);
    }

export const submissionAllList = (

 options?: SecondParameter<typeof createInstance<Submission[]>>,) => {
      return createInstance<Submission[]>(
      {url: `/submission/all/`, method: 'GET'
    },
      options);
    }

export const submissionCreateCreate = (
    submission: BodyType<NonReadonly<Submission>>,
 options?: SecondParameter<typeof createInstance<OkSubmission>>,) => {
      return createInstance<OkSubmission>(
      {url: `/submission/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submission
    },
      options);
    }

/**
 * Студент видит только свои попытки. submission_id возвращается в ответе на submit.
 * @summary Результат попытки студента — оценка, покраска, правильный ответ
 */
export const submissionsRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<StudentSubmissionDetailResponse>>,) => {
      return createInstance<StudentSubmissionDetailResponse>(
      {url: `/submissions/${id}/`, method: 'GET'
    },
      options);
    }

/**
 * @summary Отправить решение контрольной задачи (сохраняется, макс. 3 попытки)
 */
export const submissionsControlSubmitCreate = (
    submitRequest: BodyType<SubmitRequest>,
 options?: SecondParameter<typeof createInstance<ControlSubmitResponse>>,) => {
      return createInstance<ControlSubmitResponse>(
      {url: `/submissions/control/submit/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submitRequest
    },
      options);
    }

/**
 * @summary Проверить решение обучающей задачи (без сохранения попытки)
 */
export const submissionsEducationCheckCreate = (
    submitRequest: BodyType<SubmitRequest>,
 options?: SecondParameter<typeof createInstance<EducationSubmitResponse>>,) => {
      return createInstance<EducationSubmitResponse>(
      {url: `/submissions/education/check/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submitRequest
    },
      options);
    }

export const taskCategoryRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkTaskCategoryCRUD>>,) => {
      return createInstance<OkTaskCategoryCRUD>(
      {url: `/task-category/${id}/`, method: 'GET'
    },
      options);
    }

export const taskCategoryDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/task-category/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const taskCategoryUpdateUpdate = (
    id: number,
    taskCategoryCRUD: BodyType<NonReadonly<TaskCategoryCRUD>>,
 options?: SecondParameter<typeof createInstance<OkTaskCategoryCRUD>>,) => {
      return createInstance<OkTaskCategoryCRUD>(
      {url: `/task-category/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taskCategoryCRUD
    },
      options);
    }

export const taskCategoryUpdatePartialUpdate = (
    id: number,
    patchedTaskCategoryCRUD: BodyType<NonReadonly<PatchedTaskCategoryCRUD>>,
 options?: SecondParameter<typeof createInstance<OkTaskCategoryCRUD>>,) => {
      return createInstance<OkTaskCategoryCRUD>(
      {url: `/task-category/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedTaskCategoryCRUD
    },
      options);
    }

export const taskCategoryAllList = (

 options?: SecondParameter<typeof createInstance<TaskCategoryCRUD[]>>,) => {
      return createInstance<TaskCategoryCRUD[]>(
      {url: `/task-category/all/`, method: 'GET'
    },
      options);
    }

export const taskCategoryCreateCreate = (
    taskCategoryCRUD: BodyType<NonReadonly<TaskCategoryCRUD>>,
 options?: SecondParameter<typeof createInstance<OkTaskCategoryCRUD>>,) => {
      return createInstance<OkTaskCategoryCRUD>(
      {url: `/task-category/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskCategoryCRUD
    },
      options);
    }

export const taskRetrieve = (
    id: number,
 options?: SecondParameter<typeof createInstance<OkTaskAdmin>>,) => {
      return createInstance<OkTaskAdmin>(
      {url: `/task/${id}/`, method: 'GET'
    },
      options);
    }

export const taskDeleteDestroy = (
    id: number,
 options?: SecondParameter<typeof createInstance<DeletedResponse>>,) => {
      return createInstance<DeletedResponse>(
      {url: `/task/${id}/delete/`, method: 'DELETE'
    },
      options);
    }

export const taskUpdateUpdate = (
    id: number,
    taskAdmin: BodyType<NonReadonly<TaskAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskAdmin>>,) => {
      return createInstance<OkTaskAdmin>(
      {url: `/task/${id}/update/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taskAdmin
    },
      options);
    }

export const taskUpdatePartialUpdate = (
    id: number,
    patchedTaskAdmin: BodyType<NonReadonly<PatchedTaskAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskAdmin>>,) => {
      return createInstance<OkTaskAdmin>(
      {url: `/task/${id}/update/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedTaskAdmin
    },
      options);
    }

export const taskAllList = (

 options?: SecondParameter<typeof createInstance<TaskAdmin[]>>,) => {
      return createInstance<TaskAdmin[]>(
      {url: `/task/all/`, method: 'GET'
    },
      options);
    }

export const taskCreateCreate = (
    taskAdmin: BodyType<NonReadonly<TaskAdmin>>,
 options?: SecondParameter<typeof createInstance<OkTaskAdmin>>,) => {
      return createInstance<OkTaskAdmin>(
      {url: `/task/create/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskAdmin
    },
      options);
    }

/**
 * @summary Получить случайную задачу для контроля (уровень сложности 3 или 4)
 */
export const tasksControlRandomRetrieve = (

 options?: SecondParameter<typeof createInstance<ControlTaskResponse>>,) => {
      return createInstance<ControlTaskResponse>(
      {url: `/tasks/control/random/`, method: 'GET'
    },
      options);
    }

/**
 * @summary Получить задачи для обучения (по одной на каждый уровень сложности 1–4)
 */
export const tasksEducationRandomRetrieve = (

 options?: SecondParameter<typeof createInstance<EducationTasksResponse>>,) => {
      return createInstance<EducationTasksResponse>(
      {url: `/tasks/education/random/`, method: 'GET'
    },
      options);
    }

export type AdminSubmissionsRetrieveResult = NonNullable<Awaited<ReturnType<typeof adminSubmissionsRetrieve>>>
export type AdminSubmissionsAllListResult = NonNullable<Awaited<ReturnType<typeof adminSubmissionsAllList>>>
export type AnswerRetrieveResult = NonNullable<Awaited<ReturnType<typeof answerRetrieve>>>
export type AnswerDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof answerDeleteDestroy>>>
export type AnswerUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof answerUpdateUpdate>>>
export type AnswerUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof answerUpdatePartialUpdate>>>
export type AnswerAllListResult = NonNullable<Awaited<ReturnType<typeof answerAllList>>>
export type AnswerCreateCreateResult = NonNullable<Awaited<ReturnType<typeof answerCreateCreate>>>
export type AuthLoginCreateResult = NonNullable<Awaited<ReturnType<typeof authLoginCreate>>>
export type AuthLogoutCreateResult = NonNullable<Awaited<ReturnType<typeof authLogoutCreate>>>
export type AuthRefreshTokenCreateResult = NonNullable<Awaited<ReturnType<typeof authRefreshTokenCreate>>>
export type AuthRegisterAdminCreateResult = NonNullable<Awaited<ReturnType<typeof authRegisterAdminCreate>>>
export type AuthRegisterStudentCreateResult = NonNullable<Awaited<ReturnType<typeof authRegisterStudentCreate>>>
export type CategoryConfigRetrieveResult = NonNullable<Awaited<ReturnType<typeof categoryConfigRetrieve>>>
export type CategoryConfigDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof categoryConfigDeleteDestroy>>>
export type CategoryConfigUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof categoryConfigUpdateUpdate>>>
export type CategoryConfigUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof categoryConfigUpdatePartialUpdate>>>
export type CategoryConfigAllListResult = NonNullable<Awaited<ReturnType<typeof categoryConfigAllList>>>
export type CategoryConfigCreateCreateResult = NonNullable<Awaited<ReturnType<typeof categoryConfigCreateCreate>>>
export type ColorsRetrieveResult = NonNullable<Awaited<ReturnType<typeof colorsRetrieve>>>
export type ColorsDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof colorsDeleteDestroy>>>
export type ColorsUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof colorsUpdateUpdate>>>
export type ColorsUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof colorsUpdatePartialUpdate>>>
export type ColorsAllListResult = NonNullable<Awaited<ReturnType<typeof colorsAllList>>>
export type ColorsCreateCreateResult = NonNullable<Awaited<ReturnType<typeof colorsCreateCreate>>>
export type ComplexityRetrieveResult = NonNullable<Awaited<ReturnType<typeof complexityRetrieve>>>
export type ComplexityDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof complexityDeleteDestroy>>>
export type ComplexityUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof complexityUpdateUpdate>>>
export type ComplexityUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof complexityUpdatePartialUpdate>>>
export type ComplexityAllListResult = NonNullable<Awaited<ReturnType<typeof complexityAllList>>>
export type ComplexityCreateCreateResult = NonNullable<Awaited<ReturnType<typeof complexityCreateCreate>>>
export type MarkupOptionRetrieveResult = NonNullable<Awaited<ReturnType<typeof markupOptionRetrieve>>>
export type MarkupOptionDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof markupOptionDeleteDestroy>>>
export type MarkupOptionUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof markupOptionUpdateUpdate>>>
export type MarkupOptionUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof markupOptionUpdatePartialUpdate>>>
export type MarkupOptionAllListResult = NonNullable<Awaited<ReturnType<typeof markupOptionAllList>>>
export type MarkupOptionCreateCreateResult = NonNullable<Awaited<ReturnType<typeof markupOptionCreateCreate>>>
export type MarkupRetrieveResult = NonNullable<Awaited<ReturnType<typeof markupRetrieve>>>
export type MarkupDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof markupDeleteDestroy>>>
export type MarkupUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof markupUpdateUpdate>>>
export type MarkupUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof markupUpdatePartialUpdate>>>
export type MarkupAllListResult = NonNullable<Awaited<ReturnType<typeof markupAllList>>>
export type MarkupCreateCreateResult = NonNullable<Awaited<ReturnType<typeof markupCreateCreate>>>
export type ProfileRetrieveResult = NonNullable<Awaited<ReturnType<typeof profileRetrieve>>>
export type QuestionRetrieveResult = NonNullable<Awaited<ReturnType<typeof questionRetrieve>>>
export type QuestionDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof questionDeleteDestroy>>>
export type QuestionUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof questionUpdateUpdate>>>
export type QuestionUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof questionUpdatePartialUpdate>>>
export type QuestionAllListResult = NonNullable<Awaited<ReturnType<typeof questionAllList>>>
export type QuestionCreateCreateResult = NonNullable<Awaited<ReturnType<typeof questionCreateCreate>>>
export type SchemaRetrieveResult = NonNullable<Awaited<ReturnType<typeof schemaRetrieve>>>
export type SubmissionRetrieveResult = NonNullable<Awaited<ReturnType<typeof submissionRetrieve>>>
export type SubmissionDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof submissionDeleteDestroy>>>
export type SubmissionUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof submissionUpdateUpdate>>>
export type SubmissionUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof submissionUpdatePartialUpdate>>>
export type SubmissionAllListResult = NonNullable<Awaited<ReturnType<typeof submissionAllList>>>
export type SubmissionCreateCreateResult = NonNullable<Awaited<ReturnType<typeof submissionCreateCreate>>>
export type SubmissionsRetrieveResult = NonNullable<Awaited<ReturnType<typeof submissionsRetrieve>>>
export type SubmissionsControlSubmitCreateResult = NonNullable<Awaited<ReturnType<typeof submissionsControlSubmitCreate>>>
export type SubmissionsEducationCheckCreateResult = NonNullable<Awaited<ReturnType<typeof submissionsEducationCheckCreate>>>
export type TaskCategoryRetrieveResult = NonNullable<Awaited<ReturnType<typeof taskCategoryRetrieve>>>
export type TaskCategoryDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof taskCategoryDeleteDestroy>>>
export type TaskCategoryUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof taskCategoryUpdateUpdate>>>
export type TaskCategoryUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof taskCategoryUpdatePartialUpdate>>>
export type TaskCategoryAllListResult = NonNullable<Awaited<ReturnType<typeof taskCategoryAllList>>>
export type TaskCategoryCreateCreateResult = NonNullable<Awaited<ReturnType<typeof taskCategoryCreateCreate>>>
export type TaskRetrieveResult = NonNullable<Awaited<ReturnType<typeof taskRetrieve>>>
export type TaskDeleteDestroyResult = NonNullable<Awaited<ReturnType<typeof taskDeleteDestroy>>>
export type TaskUpdateUpdateResult = NonNullable<Awaited<ReturnType<typeof taskUpdateUpdate>>>
export type TaskUpdatePartialUpdateResult = NonNullable<Awaited<ReturnType<typeof taskUpdatePartialUpdate>>>
export type TaskAllListResult = NonNullable<Awaited<ReturnType<typeof taskAllList>>>
export type TaskCreateCreateResult = NonNullable<Awaited<ReturnType<typeof taskCreateCreate>>>
export type TasksControlRandomRetrieveResult = NonNullable<Awaited<ReturnType<typeof tasksControlRandomRetrieve>>>
export type TasksEducationRandomRetrieveResult = NonNullable<Awaited<ReturnType<typeof tasksEducationRandomRetrieve>>>
